### ISSUE TITLE
Links to Wiki Wrong.

### ISSUE THREAD

**Issue by Ti-Mobeil** [sudojunior/tycoon-research#1]
Links to wiki for Airline Pilot and Heli Pilot Job Page not working. 

**Wrong Links:**
- https://dash.tycoon.community/wiki/Airline_Pilot
- https://dash.tycoon.community/wiki/Helicopter_Pilot

**Correct Links:**
- https://dash.tycoon.community/wiki/index.php/Helicopter_Pilot
- https://dash.tycoon.community/wiki/index.php/Airline_Pilot

**Comment by sudojunior** [comment]
Thank you @Ti-Mobeil, merged in 1c2560f.
