### ISSUE TITLE
possibly use some form of remote system for easily obtaining data

### ISSUE THREAD

**Issue by sadboilogan** [sudojunior/tycoon-research#3]
Where you may need pictures or so, i have come up with an idea for obtaining such data pretty easily and automatically, without "cheats" or macros, but by utilising FiveM features - dm me on discord if this is anything useful possibly, as im a lazy arse and dont read GH notifs

**Comment by sudojunior** [comment]
Hi Logan, Thank you for the suggestion.
Though I would like the support the idea of validating data entry, I don't think my drive folder would back me up on that.

I would be able to get 100 GB on One Google or have submitters upload to an image host (i.e. Imgur), but then that becomes very labor intensive to ensure that all entries are valid.
ref 1: https://one.google.com/storage
ref 2: https://imgur.com/

_I'll leave this open for a little while to see if anything else may turn up._
